name: Build-Docker-Image

on:
  workflow_dispatch:

env:
  DOCKER_PUSH_TOKEN: ${{ secrets.DOCKER_PUSH_TOKEN  }}
  DOCKER_PUSH_ACCOUNT: "kevinaird"

jobs:
  build:
    name: Build and Push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKER_PUSH_ACCOUNT }}
          password: ${{ env.DOCKER_PUSH_TOKEN }}
      
      - name: Set env
        run: echo "DOCKER_LATEST_TAG=$(date +%s)" >> $GITHUB_ENV
        
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ${{env.DOCKER_PUSH_ACCOUNT}}/grafana-report:${DOCKER_LATEST_TAG} --tag ${{env.DOCKER_PUSH_ACCOUNT}}/grafana-report:latest
        
      - name: Push to docker hub
        run: |
          docker push ${{env.DOCKER_PUSH_ACCOUNT}}/grafana-report:${DOCKER_LATEST_TAG}
          docker push ${{env.DOCKER_PUSH_ACCOUNT}}/grafana-report:latest