name: Unit-Test

on:
  workflow_dispatch:

jobs:
  build:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Start up influx and grafana stack
        run: cd test && docker-compose up -d --wait
      
      - name: Setup JMeter Plugins
        run: |
          cd test/jmeter
          mkdir plugins
          cd plugins
          wget https://github.com/sfakrudeen78/JMeter-InfluxDB-Writer/releases/download/v-1.2.2/JMeter-InfluxDB-Writer-plugin-1.2.2.jar

      - name: Run JMeter Test
        run: |
          docker run --rm \
            --name jmeter \
            --network host \
            -v $(pwd)/jmeter:/jmeter \
            -v $(pwd)/jmeter/plugins:/plugins \
            justb4/jmeter -n \
            -t /jmeter/test.jmx \
            -j /jmeter/jmeter.log
      
      - name: Build Grafana Report image
        run: docker build . --file Dockerfile --tag kevinaird/grafana-report-unit-test
      
      - name: Run unit tests
        run: |
          docker run --rm \
            --name grafana-report-unit-test \
            --entrypoint npm \
            --network host \
            kevinaird/grafana-report-unit-test run test
